name: Scheduled Contract Testing

on:
  workflow_call:
    inputs:
      test-target:
        type: string
        required: true
        default: '*'

  workflow_dispatch: # Manual trigger

jobs:
  contract-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: jdx/mise-action@v2.0.2
        with:
          version: 2025.8.21
      - run: mise run test:schemathesis:${{ inputs.test-target }} --phases examples

      - name: Upload test results
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: schemathesis-report-${{ inputs.test-target }}
          path: openapi/**/schemathesis-report/*
